// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version: "1.0",
	//Host:             "localhost:1923",
	//Host:             "bora78.asuscomm.com:1453",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Person API",
	Description:      "Bu API, kişileri listelemek, eklemek ve isim bazında sorgulamak için kullanılır.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate, // Boylece "swag init" deyince swagger ezilmeyecek dockTemplate (swagger_template.go)'dan yuklenecek.
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
